#--------------------------------------------------------
# AWStats-Theme-HomePage
# 项目地址：https://github.com/lete114/AWStats-Theme-HomePage
# 演示地址：https://www.imlete.cn/
# 一个静态个人主页
#--------------------------------------------------------

title: Lete乐特的小窝
author: Lete乐特
favicon: /img/favicon.ico
avatar: /img/avatar.png
description: 我相信我可以，但我一直在路上，所以我有无限的可能！！
keywords: Lete乐特,Developer,Programmer,Coder
about: 人生只有一次，大胆的生活！
error: 404 Not Found

social:
  <img src="/svg/blog.svg" alt="blog"/>: https://blog.imlete.cn
  <img src="/svg/mail.svg" alt="mail"/>: mailto:i@lete114.top
  <img src="/svg/github.svg" alt="github/lete114"/>: https://github.com/Lete114
  <img src="/svg/link.svg" alt="link"/>: https://blog.imlete.cn/link

main:
  - h2: Hi there, I'm Lete
    content: |
      为什么我叫 <strong>Lete乐特</strong> ？因为我小时候叫 <strong>乐特</strong>，后来改了名字，我依旧很喜欢 <strong>Lete乐特</strong> 这个名字

  - h2: 我的编程之旅
    content: |
      我是一名 WEB 前端开发者，在我小学的时候，因为一款游戏 <a href="https://www.minecraft.net" target="_blank">Minecraft</a>
      ，当时只能用手机玩，为了让游戏更有趣，很多人都和我一样，使用了 <a href="https://github.com/zhuowei/MCPELauncher" target="_blank">Minecraft PE Block Launcher</a>
      来添加更多玩法，当时有插件(.apk)、脚本(.js)、模组(.mod，不过貌似在PE版本0.8.1过后这一项技术就失传了)
      ，从那时起我就开始接触 JavaScript，<strong>我便开始了我的编程之旅</strong>，后来接触了PC版的 1.7.10 版本我开始使用别人制作的 mod 
      ，因为 mod 需要通过 <a href="https://github.com/MinecraftForge/MinecraftForge" target="_blank">Minecraft Forge</a>
      加载，所以学习了 Java 再后来我发现我并不是学 Java 的料，于是就开始自学前端

# 自定义引入外部css、js
import:
  head: # 引入到</head>之前
    -
  top: # 引入到<body>之后
    -
  bottom: # 引入到</body>之前
    -
  # 例如：
  # - <link rel="stylesheet" href="/css/index.css">
  # - '<style>body{color: red}</style>' ## 注意由于css的‘{}’是关键符号所以需要(单/双)引号''
  # - <script>alert(1)</script>

# 页脚
footer:
  ## 搭建年份
  since: 2019
  ## 自定义内容，支持 HTML
  customText:

CDN:
  main_css: /css/main.css
